# Generated by Django 5.1.1 on 2024-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('business_location', models.TextField()),
                ('business_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_updated_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
